apiVersion: v1
kind: Service
metadata:
  name: tigera-manager-nodeport
  namespace: tigera-manager
spec:
  type: NodePort
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
    nodePort: 32000
  selector:
    k8s-app: tigera-manager
  sessionAffinity: None
status:
  loadBalancer: {}
