apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tigera-elasticsearch
  local:
# This path specifies the directory on the Node which is the mount target. Ensure this directory is created
    path: /var/log/calico-ee
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
# Specifies which value (node) the Persistant Volume is bound to
          - k8s-master-01
          - k8s-worker-01
